/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

public char findTheDifference(String s, String t) {
    char c ='.';
    int[] alphabet = new int[26];
    for (int i = 0; i < s.length(); i++) {
        alphabet[s.charAt(i)-'a'] += 1;
    }
    for (int i = 0; i < t.length(); i++) {
        c = t.charAt(i);
        alphabet[c-'a'] -=1;
        if (alphabet[c-'a'] < 0) {
            return c;
        }
    }
    return c;
}

/*
"abcd"
"abddc"
*/